name: smart_home_prject_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  provider: ^6.1.1
  font_awesome_flutter: ^10.1.0
  charts_flutter: ^0.12.0
  sqflite: ^2.0.0+3
  flutter_facebook_auth: ^4.3.3
  syncfusion_flutter_gauges: ^20.2.37
  shared_preferences: ^2.0.12
  google_sign_in: ^5.4.2
  #  flutter_local_notifications: ^12.0.3
  google_maps_flutter: ^2.2.8
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  location: ^5.0.3
  proximity_sensor: ^1.0.4
  sensors_plus: ^5.0.0
  path_provider: ^2.0.11  
  flutter_speed_dial: ^7.0.0
  light_sensor: ^3.0.0
  fl_chart:
    path: ../fl_chart  # Local path to the cloned repository
  flutter_local_notifications: ^17.1.2
  syncfusion_flutter_charts: ^20.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Mrius_24.jpg
    - lib/assets/bulb.png
    - lib/assets/turn-off.jpg
